### ISSUE TITLE
Code sprint to plan code (re-)structuring

### ISSUE THREAD

**Issue by benedikt-voelkel** [mconcas/o2tuner#22]
- [x] use logging facility to handle severity of errors and for instance quit automatically on what we would call "fatal" or "error", see also #21 
- [x] develop a clear package strategy of python files in the `o2tuner` package
- [ ] follow up on upcoming point in dedicated issues
- [ ] update/adjust/refine `pylint` and `flake8` test settings

**Comment by mconcas** [comment]
Meta issue moved to milestone
